import { test, expect } from '@playwright/test'

test('month browsing, global search and returning to the same list position work with hundreds of pages', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto('/?demo=judge')
  await page.getByRole('button', { name: '画册', exact: true }).click()
  await expect(page.getByRole('heading', { name: '十月', exact: true })).toBeVisible()
  await expect(page.locator('.album-record-card')).toHaveCount(3)
  await page.getByRole('button', { name: '2026年9月', exact: true }).click()
  await expect(page.locator('.album-record-card')).toHaveCount(12)
  await page.getByRole('button', { name: /再翻/ }).click()
  const last = page.locator('.album-record-card').last()
  await last.scrollIntoViewIfNeeded()
  const scrollBefore = await page.evaluate(() => window.scrollY)
  expect(scrollBefore).toBeGreaterThan(100)
  const label = await last.getAttribute('aria-label')
  const count = await page.locator('.album-record-card').count()
  await last.click()
  await page.getByRole('button', { name: '← 返回九月目录' }).click()
  await expect(page.locator('.album-record-card')).toHaveCount(count)
  await expect(page.getByRole('button', { name: label! })).toBeFocused()
  expect(Math.abs(await page.evaluate(() => window.scrollY) - scrollBefore)).toBeLessThan(3)
  await page.getByRole('searchbox', { name: '搜索全部记录' }).fill('台灯')
  await expect(page.getByText('搜索范围：全部月份')).toBeVisible()
  await expect(page.locator('.album-record-card')).toHaveCount(12)
  await expect(page.locator('.album-record-card mark').first()).toHaveText('台灯')
  await page.locator('.album-record-card').first().click()
  await page.getByRole('button', { name: '原话与理解' }).click()
  await expect(page.locator('.daily-message-user')).toContainText('台灯')
  await page.getByRole('button', { name: '← 返回搜索结果' }).click()
  await expect(page.getByRole('searchbox')).toHaveValue('台灯')
  await page.getByRole('button', { name: '对话', exact: true }).click()
  await page.getByRole('button', { name: '画册', exact: true }).click()
  await expect(page.getByRole('searchbox')).toHaveValue('台灯')
  await page.getByRole('searchbox').fill('不存在的片段xyz')
  await expect(page.getByText('还没找到这个片刻')).toBeVisible()
  await page.getByRole('button', { name: '返回月份目录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '九月', exact: true })).toBeVisible()
})

test('mobile month chooser reaches older years and reading skips missing days', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/?demo=judge')
  await page.getByRole('button', { name: '画册', exact: true }).click()
  await page.getByLabel('选择月份', { exact: true }).click()
  await page.getByLabel('选择月份', { exact: true }).press('Escape')
  await expect(page.locator('.album-month-chooser')).not.toHaveAttribute('open', '')
  await page.getByLabel('选择月份', { exact: true }).click()
  await page.locator('.album-month-chooser .album-year > summary').filter({ hasText: '2025' }).click()
  await page.getByRole('button', { name: '2025年3月', exact: true }).click()
  await expect(page.getByRole('heading', { name: '三月', exact: true })).toBeVisible()
  await expect(page.locator('.album-month-chooser')).not.toHaveAttribute('open', '')
  await expect(page.locator('.album-record-card').first()).toHaveAttribute('aria-label', /2025年3月/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '回到今天 ↗' }).click()
  await expect(page.getByRole('button', { name: '下一条记录 →' })).toBeDisabled()
  await page.getByRole('button', { name: '← 上一条记录' }).click()
  await expect(page.locator('.daily-heading')).toContainText('2026.10.02')
  await page.getByRole('button', { name: '下一条记录 →' }).click()
  await expect(page.locator('.daily-heading')).toContainText('2026.10.04')
  await page.getByRole('button', { name: '← 返回三月目录' }).click()
  await expect(page.getByRole('heading', { name: '三月', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
