import { expect, test, type Page } from '@playwright/test'

async function mockModels(page: Page) {
  await page.route('**/api/ai/model-status', (route) => route.fulfill({ json: { status: 'ready', model: { provider: 'qwen', id: 'fake-qwen' } } }))
  await page.route('**/api/ai/private-chat', (route) => route.fulfill({ json: { status: 'generated', reply: '把想法说出来，也让你自己看得更清楚了。', nextQuestion: null, citations: [], model: { provider: 'qwen', id: 'fake-qwen' }, generatedAt: new Date().toISOString() } }))
}
async function send(page: Page, text: string) {
  await page.getByRole('textbox', { name: '发送消息' }).fill(text)
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.locator('.product-ai-reply').last()).toBeVisible()
}

test('complete text and replies survive reload; front, reverse, edit and Markdown download form one flow', async ({ page }) => {
  await mockModels(page)
  let sentMessages: { id: string; role: string; text: string }[] = []
  await page.route('**/api/ai/daily-album', async (route) => {
    sentMessages = route.request().postDataJSON().messages
    const user = sentMessages.find((m) => m.role === 'user')!
    await route.fulfill({ json: { status: 'generated', title: '讲给朋友听的一天', diary: '今天把项目讲给朋友听。开始有些紧张，后来发现思路逐渐清楚，心情也轻松了一点。', portrait: { facts: ['介绍了自己的项目。'], feelings: ['自述最后很开心。'], observations: [{ text: '这次讲述帮助了思路整理。', evidenceIds: [user.id] }], uncertainties: ['尚不能判断长期偏好。'] }, model: { provider: 'qwen', id: 'fake-qwen' }, generatedAt: new Date().toISOString() } })
  })
  await page.goto('/')
  const original = '今天讲了项目。' + '这是当天的详细经过。'.repeat(90) + '最后其实很开心。'
  await send(page, original)
  await page.getByRole('textbox', { name: '发送消息' }).fill('还没有发出的草稿')
  await page.reload()
  await expect(page.getByRole('textbox', { name: '发送消息' })).toHaveValue('还没有发出的草稿')
  await expect(page.locator('.product-ai-reply')).toContainText('把想法说出来')
  await page.getByRole('button', { name: '看看今天这一页' }).click()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.locator('.daily-message-user')).toContainText(original)
  await expect(page.locator('.daily-message-assistant')).toContainText('把想法说出来')
  await page.getByRole('button', { name: '整理今天', exact: true }).click()
  await expect(page.locator('.daily-status')).toHaveText('已整理')
  expect(sentMessages.find((m) => m.role === 'user')?.text).toBe(original)
  await page.getByRole('button', { name: '日记正面', exact: true }).click()
  await expect(page.getByRole('heading', { name: '讲给朋友听的一天' })).toBeVisible()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await page.getByRole('button', { name: '编辑 Markdown' }).click()
  const markdown = page.getByLabel('每日记录 Markdown')
  const text = await markdown.inputValue()
  await markdown.fill(text.replace(original, '修正：其实只是练习讲述，还没有见朋友。'))
  await page.getByRole('button', { name: '预览修改' }).click()
  await page.getByRole('button', { name: '保存 Markdown 修改' }).click()
  await expect(page.locator('.daily-message-user')).toContainText('其实只是练习讲述')
  await expect(page.locator('.daily-portrait')).not.toContainText('介绍了自己的项目')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /下载 .md/ }).click()
  expect((await download).suggestedFilename()).toMatch(/^\d{4}-\d{2}-\d{2}\.md$/)
  await page.reload()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '画册', exact: true }).click()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.locator('.daily-message-user')).toContainText('其实只是练习讲述')
  await expect(page.locator('.storage-warning')).toHaveCount(0)
})

test('empty sample is isolated from real records and usable on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await mockModels(page)
  let calls = 0
  await page.route('**/api/ai/daily-album', (route) => { calls++; return route.abort() })
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button', { name: '画册', exact: true }).click()
  await expect(page.getByText('合成示例', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.getByRole('heading', { name: '今日肖像' })).toBeVisible()
  expect(calls).toBe(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('navigation').getByRole('button', { name: '对话', exact: true }).click()
  await expect(page.locator('.product-bubble-row.user')).toHaveCount(0)
})

test('clear requires confirmation and removes saved records and draft', async ({ page }) => {
  await mockModels(page)
  await page.goto('/')
  await send(page, '待清除的合成测试记录。')
  await page.getByRole('button', { name: '清除本次内容' }).click()
  await page.getByRole('button', { name: '保留记录' }).click()
  await expect(page.locator('.product-bubble-row.user')).toContainText('待清除')
  await page.getByRole('button', { name: '清除本次内容' }).click()
  await page.getByRole('button', { name: '确认清除本机记录' }).click()
  await page.reload()
  await expect(page.locator('.product-bubble-row.user')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button', { name: '画册', exact: true }).click()
  await expect(page.getByText('合成示例', { exact: true })).toBeVisible()
})

test('failed generation retains original text and cannot claim a generated diary', async ({ page }) => {
  await mockModels(page)
  await page.route('**/api/ai/daily-album', (route) => route.fulfill({ status: 503, json: { status: 'error' } }))
  await page.goto('/')
  await send(page, '整理失败也要保留下来的合成原话。')
  await page.getByRole('button', { name: '看看今天这一页' }).click()
  await page.getByRole('button', { name: '整理今天', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('原文已保留')
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.locator('.daily-message-user')).toContainText('整理失败也要保留下来')
  await expect(page.locator('.daily-status')).toHaveText('原话已收录')
})

test('a control-only conversation stays in its dated archive after reload', async ({ page }) => {
  await mockModels(page)
  await page.goto('/')
  await page.getByRole('textbox', { name: '发送消息' }).fill('今天先不聊了')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByRole('button', { name: '看看今天这一页' }).click()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.locator('.daily-message-user')).toContainText('今天先不聊了')
  await expect(page.locator('.daily-message-system').last()).toBeVisible()
  await page.reload()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '画册', exact: true }).click()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.locator('.daily-message-user')).toContainText('今天先不聊了')
})

test('damaged cache is preserved, can be backed up and never reports a successful save', async ({ page }) => {
  await mockModels(page)
  await page.addInitScript(() => localStorage.setItem('jianzhi:local-session:v1', 'damaged synthetic cache'))
  await page.goto('/')
  await expect(page.locator('.storage-warning')).toContainText('原缓存未被清除')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载原缓存备份' }).click()
  expect((await download).suggestedFilename()).toBe('渐知-本机缓存备份.json')
  await page.getByRole('textbox', { name: '发送消息' }).fill('不能覆盖旧缓存的草稿')
  expect(await page.evaluate(() => localStorage.getItem('jianzhi:local-session:v1'))).toBe('damaged synthetic cache')
  await expect(page.locator('.messenger-input-hint')).toContainText('保存遇到问题')
})

test('storage quota failure keeps the record available for Markdown download', async ({ page }) => {
  await mockModels(page)
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('full', 'QuotaExceededError') } })
  await page.goto('/')
  await send(page, '浏览器空间满了也不能丢的合成原话。')
  await expect(page.locator('.storage-warning')).toContainText('本机保存失败')
  await page.getByRole('button', { name: '看看今天这一页' }).click()
  await page.getByRole('button', { name: '记录背面', exact: true }).click()
  await expect(page.locator('.daily-message-user')).toContainText('不能丢的合成原话')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /下载 .md/ }).click()
  expect((await download).suggestedFilename()).toMatch(/\.md$/)
})

test('date navigation protects an unfinished diary edit', async ({ page }) => {
  await mockModels(page)
  await page.goto('/')
  await send(page, '第一天的合成记录。')
  await page.getByLabel('邀请节奏与演示日期', { exact: true }).click()
  await page.getByRole('button', { name: '推进到第 2 天' }).click()
  await send(page, '第二天的合成记录。')
  await page.getByRole('button', { name: '看看今天这一页' }).click()
  await page.getByRole('button', { name: '编辑日记', exact: true }).click()
  await page.getByLabel('日记正文').fill('正在写的日记')
  await page.getByRole('button', { name: '查看第 1 天' }).click()
  await expect(page.getByLabel('日记正文')).toHaveValue('正在写的日记')
  await expect(page.locator('.free-status')).toContainText('画册正在编辑')
  await page.getByRole('button', { name: '保存日记', exact: true }).click()
  await page.getByRole('button', { name: '查看第 1 天' }).click()
  await expect(page.locator('.daily-album')).toContainText('第一天的合成记录')
})
