import { test, expect } from '@playwright/test'
import { DEMO_ROUNDS } from '../src/features/judge/judgeScript'

test('preserves the original call layout and shares the preset flow with restored voice tools', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.route('**/api/**', route => route.abort())
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  // Read the original screen in a disposable browser context, without requesting a microphone.
  await page.goto('/')
  await page.getByRole('button', { name: '语音对话', exact: true }).click()
  const callShape = () => page.locator('.product-call-portrait, .product-call-actions, .product-call-mic, .product-call-exit').evaluateAll(elements => elements.map(element => {
    const style = getComputedStyle(element)
    return { width: style.width, height: style.height, borderRadius: style.borderRadius, gap: style.gap, background: style.backgroundColor }
  }))
  const originalShape = await callShape()
  await page.goto('/?demo=judge')
  await page.getByLabel('选择伙伴', { exact: true }).click()
  await page.getByRole('button', { name: '小笺，女性形象' }).click()
  await expect(page.getByRole('heading', { name: '小笺', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '开始语音输入' }).click()
  await expect(page.getByLabel('语音输入示例')).toBeVisible()
  await page.getByRole('button', { name: '停止聆听并放弃本次语音' }).click()
  await expect(page.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[0].user)
  await page.getByRole('button', { name: '开始语音输入' }).click()
  await page.getByRole('button', { name: '结束聆听并转成文字' }).click()
  await expect(page.locator('.product-bubble-row.user')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '发送', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: '语音对话', exact: true }).click()
  expect(await callShape()).toEqual(originalShape)
  const call = page.getByRole('region', { name: '渐记语音通话' })
  await expect(call.getByRole('img')).toHaveAttribute('src', /jianji-xiaojian-cutout\.png$/)
  await page.getByRole('button', { name: '开始语音对话聆听' }).click()
  await page.getByRole('button', { name: '说完了，转写并发送' }).click()
  await expect(call).toContainText(DEMO_ROUNDS[0].reply)
  await page.getByRole('button', { name: '退出语音通话' }).press('Escape')
  await expect(page.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
  await expect(page.getByRole('button', { name: '语音对话', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('keeps the new album and conversation content while restoring the original chat tools at 320px', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/?demo=judge')
  await expect(page.getByRole('button', { name: '发送', exact: true })).toBeInViewport()
  await page.getByLabel('选择伙伴', { exact: true }).click()
  await expect(page.getByRole('button', { name: '慢慢，中性形象' })).toBeInViewport()
  await page.getByRole('button', { name: '慢慢，中性形象' }).click()
  await page.getByRole('button', { name: '语音对话', exact: true }).click()
  await expect(page.getByRole('button', { name: '开始语音对话聆听' })).toBeInViewport()
  await expect(page.getByRole('button', { name: '退出语音通话' })).toBeInViewport()
  await page.getByRole('button', { name: '退出语音通话' }).click()
  await page.getByRole('button', { name: '画册', exact: true }).click()
  await expect(page.getByRole('heading', { name: '十月', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '回到今天 ↗' }).click()
  await expect(page.getByRole('button', { name: '日常小记' })).toBeVisible()
  await page.getByRole('button', { name: '原话与理解' }).click()
  await expect(page.getByRole('region', { name: '每日画册' })).toContainText('原话与今日肖像')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
