import { test, expect } from '@playwright/test'
import { DEMO_ROUNDS } from '../src/features/judge/judgeScript'

test('daily samples preserve a reply in progress and link back to the current diary without APIs', async ({ page }) => {
  const apiCalls: string[] = []
  const errors: string[] = []
  await page.route('**/api/**', route => { apiCalls.push(route.request().url()); return route.abort() })
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?demo=judge')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByRole('button', { name: '日常', exact: true }).click()
  const daily = page.getByRole('region', { name: '日常生活记录' })
  await expect(daily).toBeVisible()
  await expect(page.getByRole('button', { name: '日常', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(daily).toContainText('2,360')
  await expect(daily).toContainText('15:00')
  await daily.getByRole('button', { name: '查看2026年10月3日的日常', exact: true }).click()
  await expect(daily).toContainText('8,926')
  await daily.getByRole('button', { name: '查看消费明细', exact: true }).click()
  await expect(daily.getByRole('table').first()).toBeVisible()
  await daily.getByText('数据来源', { exact: true }).click()
  await daily.getByLabel('显示消费示例').uncheck()
  await expect(daily.getByRole('table')).toHaveCount(0)
  await daily.getByRole('button', { name: '回到对话', exact: true }).click()
  const chat = page.getByRole('region', { name: '对话记录' })
  await expect(chat.getByText(DEMO_ROUNDS[0].reply, { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
  await expect(chat.locator('.product-bubble-row.user')).toHaveCount(1)
  await page.getByRole('button', { name: '日常', exact: true }).click()
  await expect(daily.getByLabel('显示消费示例')).not.toBeChecked()
  await daily.getByRole('button', { name: '翻开今天的画册', exact: true }).click()
  await expect(page.getByRole('region', { name: '每日画册' })).toContainText('好久没这么开心了')
  await page.getByRole('button', { name: '重新体验', exact: true }).click()
  await page.getByRole('button', { name: '日常', exact: true }).click()
  await page.getByText('数据来源', { exact: true }).click()
  await expect(daily.getByLabel('显示消费示例')).toBeChecked()
  expect(apiCalls).toEqual([])
  expect(errors).toEqual([])
})

test('daily care opens only the user quotes already shared that day', async ({ page }) => {
  await page.goto('/?demo=judge')
  for (let round = 0; round < 3; round++) {
    await page.getByRole('button', { name: '发送', exact: true }).click()
    await expect(page.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[round + 1].user)
  }
  await page.getByRole('button', { name: '日常', exact: true }).click()
  const daily = page.getByRole('region', { name: '日常生活记录' })
  const care = daily.getByRole('region', { name: '知知的一点关心' })
  await care.getByRole('button', { name: '来自你今天说的话', exact: true }).click()
  const source = page.getByRole('dialog', { name: '这句话的来处' })
  await expect(source).toBeVisible()
  await expect(source.locator('blockquote')).toHaveCount(1)
  await expect(source.getByText(DEMO_ROUNDS[2].user, { exact: true })).toBeVisible()
  await expect(source.getByText(DEMO_ROUNDS[3].user, { exact: true })).toHaveCount(0)
  await source.getByRole('button', { name: '回到阅读', exact: true }).click()
  await daily.getByRole('button', { name: '回到对话', exact: true }).click()
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[4].user)
  await page.getByRole('button', { name: '日常', exact: true }).click()
  await care.getByRole('button', { name: '来自你今天说的话', exact: true }).click()
  await expect(source.locator('blockquote')).toHaveCount(3)
  for (const round of [1, 2, 3]) await expect(source.getByText(DEMO_ROUNDS[round].user, { exact: true })).toBeVisible()
  await expect(source.locator('blockquote small')).toHaveText(['用户原话', '用户原话', '用户原话'])
  await source.getByRole('button', { name: '回到阅读', exact: true }).click()
  await daily.getByRole('button', { name: '查看2026年10月3日的日常', exact: true }).click()
  await expect(care.getByRole('button', { name: '来自你今天说的话', exact: true })).toHaveCount(0)
  await daily.getByRole('button', { name: '查看2026年10月4日的日常', exact: true }).click()
  await daily.getByText('数据来源', { exact: true }).click()
  for (const name of ['显示步数示例', '显示心率示例', '显示消费示例']) await daily.getByLabel(name).uncheck()
  await expect(care.getByRole('button', { name: '来自你今天说的话', exact: true })).toHaveCount(0)
  await expect(care).toContainText('由你选择显示哪些示例')
})

for (const width of [320, 375]) {
  test(`daily records and three navigation entries fit a ${width}px screen`, async ({ page }) => {
    await page.setViewportSize({ width, height: 812 })
    await page.goto('/?demo=judge')
    for (const name of ['对话', '画册', '日常']) {
      await expect(page.getByRole('button', { name, exact: true })).toBeInViewport()
    }
    await page.getByRole('button', { name: '日常', exact: true }).click()
    const daily = page.getByRole('region', { name: '日常生活记录' })
    await daily.getByRole('button', { name: '查看心率明细', exact: true }).click()
    await expect(daily.getByRole('table').first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await daily.getByText('数据来源', { exact: true }).click()
    for (const name of ['显示步数示例', '显示心率示例', '显示消费示例']) await daily.getByLabel(name).uncheck()
    await expect(daily.getByRole('table')).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await daily.getByRole('button', { name: '回到对话', exact: true }).click()
    await expect(page.getByRole('button', { name: '发送', exact: true })).toBeInViewport()
  })
}
