import { expect, test } from '@playwright/test'

test.use({ timezoneId: 'Asia/Shanghai' })

test('the conversation is home and an unfinished draft survives tab changes', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('region', { name: '对话记录' })).toBeVisible()
  await expect(page.getByText('演示版会将一般消息记入画册；可随时修改或删除。')).toBeVisible()
  await expect(page.getByRole('navigation', { name: '产品导航' }).getByRole('button')).toHaveCount(3)
  await expect(page.getByText('今天有什么想记下的？')).toBeVisible()
  await page.getByRole('textbox', { name: '发送消息' }).fill('今天去了河边。')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('今天去了河边。')
  await page.getByRole('textbox', { name: '发送消息' }).fill('明天还想继续写')
  await page.getByRole('button', { name: '画册' }).click()
  await expect(page.getByRole('article', { name: '第 1 天画册页' })).toContainText('今天去了河边。')
  await expect(page.getByRole('navigation', { name: '有记录日期' }).getByRole('button')).toHaveCount(1)
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '对话' }).click()
  await expect(page.getByRole('textbox', { name: '发送消息' })).toHaveValue('明天还想继续写')
})

test('historical album browsing never advances the active invitation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '发送消息' }).fill('第一天的原话。')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByText('邀请节奏与演示日期').click()
  await page.getByRole('button', { name: '推进到第 2 天' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('第 2 天 · 第 1 题')
  await page.getByRole('textbox', { name: '发送消息' }).fill('随手记：第二天的一句话。')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByRole('button', { name: '画册' }).click()
  await page.getByRole('button', { name: '查看第 1 天' }).click()
  await expect(page.getByRole('article', { name: '第 1 天画册页' })).toBeVisible()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '对话' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('第 2 天 · 第 1 题')
  await expect(page.getByRole('textbox', { name: '发送消息' })).toBeVisible()
})

test('editing and deleting an answer updates the conversation and album together', async ({ page }) => {
  const old = '只给自己看的旧原话。'
  const revised = '重新写过的原话。'
  await page.goto('/')
  await page.getByRole('textbox', { name: '发送消息' }).fill(old)
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByRole('button', { name: '画册' }).click()
  await page.getByRole('button', { name: '修改这条原话' }).click()
  await page.getByRole('textbox', { name: '修改原话' }).fill(revised)
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '对话' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText(revised)
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText(old)
  await page.getByRole('button', { name: '画册' }).click()
  await page.getByRole('button', { name: '删除这条原话' }).click()
  await expect(page.getByText('画册还没有第一页')).toBeVisible()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '对话' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText(revised)
})

test('data consent is per source and refresh clears both consent and private words', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '发送消息' }).fill('只在此页停留的字。')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await page.getByRole('button', { name: '生活数据' }).click()
  await expect(page.getByRole('img', { name: /七日图表/ })).toHaveCount(0)
  await page.getByRole('button', { name: '开启手表步数模拟授权' }).click()
  await expect(page.getByRole('img', { name: /手表步数七日图表/ })).toBeVisible()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '对话' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('只在此页停留的字。')
  await page.getByRole('button', { name: '生活数据' }).click()
  await expect(page.getByRole('img', { name: /手表步数七日图表/ })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText('只在此页停留的字。')
  await page.getByRole('button', { name: '生活数据' }).click()
  await expect(page.getByRole('img', { name: /七日图表/ })).toHaveCount(0)
})

for (const width of [375, 1440]) {
  test(`product layout at ${width}px keeps the composer and navigation separate`, async ({ page }) => {
    await page.setViewportSize({ width, height: 812 })
    await page.goto('/')
    await expect(page.getByRole('region', { name: '对话记录' })).toBeVisible()
    await page.getByRole('textbox', { name: '发送消息' }).fill('今天看到了窗边的一束光。')
    await page.getByRole('button', { name: '发送', exact: true }).click()
    const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
    expect(horizontalOverflow).toBeLessThanOrEqual(0)
    if (width === 375) {
      const nav = await page.getByRole('navigation', { name: '产品导航' }).boundingBox()
      const composer = await page.locator('.product-composer').boundingBox()
      expect(nav).not.toBeNull()
      expect(composer).not.toBeNull()
      expect(composer!.y + composer!.height).toBeLessThanOrEqual(nav!.y)
    }
    await page.screenshot({ path: `test-results/product-chat-${width}.png` })
    await page.getByRole('button', { name: '画册' }).click()
    await page.screenshot({ path: `test-results/product-album-${width}.png` })
    await page.getByRole('button', { name: '生活数据' }).click()
    await page.getByRole('button', { name: '开启手表步数模拟授权' }).click()
    await page.screenshot({ path: `test-results/product-data-${width}.png` })
    if (width === 375) {
      await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
      const nav = await page.getByRole('navigation', { name: '产品导航' }).boundingBox()
      const lastNote = await page.locator('.data-footer-note').boundingBox()
      expect(lastNote).not.toBeNull()
      expect(lastNote!.y + lastNote!.height).toBeLessThanOrEqual(nav!.y)
    }
  })
}

test('a narrow phone can reach the last explicit demo-day control', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await page.getByText('邀请节奏与演示日期').click()
  const lastDay = page.getByRole('button', { name: '推进到第 9 天' })
  await lastDay.scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/product-settings-320.png' })
  const nav = await page.getByRole('navigation', { name: '产品导航' }).boundingBox()
  const dayButton = await lastDay.boundingBox()
  expect(nav).not.toBeNull()
  expect(dayButton).not.toBeNull()
  expect(dayButton!.y + dayButton!.height).toBeLessThanOrEqual(nav!.y)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
})

for (const [width, height] of [[375, 812], [320, 568]] as const) {
  test(`the composer and disclosure stay above mobile navigation after status at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height })
    await page.goto('/')
    for (const answer of ['第一句。', '第二句。']) {
      await page.getByRole('textbox', { name: '发送消息' }).fill(answer)
      await page.getByRole('button', { name: '发送', exact: true }).click()
    }
    await expect(page.getByRole('status')).toContainText('今天的记录已写入画册')
    await expect(page.getByText('演示版会将一般消息记入画册；可随时修改或删除。')).toBeVisible()
    const nav = await page.getByRole('navigation', { name: '产品导航' }).boundingBox()
    const composer = await page.locator('.product-composer').boundingBox()
    expect(nav).not.toBeNull()
    expect(composer).not.toBeNull()
    expect(composer!.y + composer!.height).toBeLessThanOrEqual(nav!.y)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `test-results/product-status-chat-${width}.png` })
  })
}

test('album comparison follows its selected day and never previews later days', async ({ page }) => {
  await page.goto('/')
  for (const [day, answer] of [[1, '第一天散步。'], [2, '第二天读书。'], [8, '第八天画画。']] as const) {
    if (day > 1) {
      if (!await page.locator('.product-settings').evaluate((element) => element.hasAttribute('open'))) {
        await page.getByText('邀请节奏与演示日期').click()
      }
      await page.getByRole('button', { name: `推进到第 ${day} 天` }).click()
    }
    await page.getByRole('textbox', { name: '发送消息' }).fill(answer)
    await page.getByRole('button', { name: '发送', exact: true }).click()
  }
  await page.getByRole('button', { name: '画册' }).click()
  const comparison = page.getByRole('region', { name: '前后两页摘录' })
  await expect(comparison).toContainText('如已有两页问答记录')
  await expect(comparison).toContainText('规则模式不判断话题是否相关或变化原因')
  await expect(comparison).toContainText('第二天读书。')
  await expect(comparison).toContainText('第八天画画。')
  await page.getByRole('button', { name: '查看第 1 天' }).click()
  await expect(comparison).toContainText('资料不足')
  await expect(comparison).not.toContainText('第八天画画。')
  await page.getByRole('button', { name: '查看第 2 天' }).click()
  await expect(comparison).toContainText('第一天散步。')
  await expect(comparison).toContainText('第二天读书。')
  await expect(comparison).not.toContainText('第八天画画。')
})

test('private excerpts label unrelated answer pairs and simulated times without claiming a shared topic', async ({ page }) => {
  await page.goto('/')
  const message = page.getByRole('textbox', { name: '发送消息' })
  const send = page.getByRole('button', { name: '发送', exact: true })
  await message.fill('今天去了河边。')
  await send.click()
  await message.fill('那时风吹得很舒服。')
  await send.click()
  await page.getByText('邀请节奏与演示日期').click()
  await page.getByRole('button', { name: '推进到第 2 天' }).click()
  await message.fill('今天又走到河边。')
  await send.click()
  await page.getByRole('button', { name: '画册' }).click()
  const excerpts = page.getByRole('region', { name: '前后两页摘录' })
  await expect(excerpts).toContainText('那时风吹得很舒服。')
  await expect(excerpts).toContainText('今天又走到河边。')
  await expect(excerpts).toContainText('不判断话题是否相关或变化原因')
  await expect(excerpts).not.toContainText('同一主题')
  const album = page.getByRole('article', { name: '第 2 天画册页' })
  await expect(album).toContainText('演示日期时间')
  await expect(album).toContainText('本次录入时间')
  await expect(album).not.toContainText('演示发生')
})

test('one message composer handles brief control phrases without putting them in the album', async ({ page }) => {
  await page.goto('/')
  const message = page.getByRole('textbox', { name: '发送消息' })
  const send = page.getByRole('button', { name: '发送', exact: true })
  await expect(send).toBeDisabled()
  await expect(page.getByRole('button', { name: '回答问题' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '主动分享' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '跳过这一题' })).toHaveCount(0)
  await message.fill('换个问题')
  await send.click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('换个问题')
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('今天有没有一个小瞬间想留在画册里？')
  await message.fill('今天先不聊了')
  await send.click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('今天先不聊了')
  await page.getByRole('button', { name: '画册' }).click()
  await expect(page.getByText('画册还没有第一页')).toBeVisible()
})

test('a mixed-content sentence and a later unsolicited message both become ordinary records', async ({ page }) => {
  await page.goto('/')
  const message = page.getByRole('textbox', { name: '发送消息' })
  const send = page.getByRole('button', { name: '发送', exact: true })
  await message.fill('今天不想答但我想记一件事：去了公园。')
  await send.click()
  await message.fill('第二句。')
  await send.click()
  await message.fill('今天的问题说完了，我还想留下一句。')
  await send.click()
  await page.getByRole('button', { name: '画册' }).click()
  const album = page.getByRole('article', { name: '第 1 天画册页' })
  await expect(album).toContainText('今天不想答但我想记一件事：去了公园。')
  await expect(album).toContainText('今天的问题说完了，我还想留下一句。')
  await expect(album).toContainText('本次页面对话')
})

test('an optional third question can be requested and declined without settling another invitation', async ({ page }) => {
  await page.goto('/')
  const message = page.getByRole('textbox', { name: '发送消息' })
  const send = page.getByRole('button', { name: '发送', exact: true })
  for (const answer of ['先记一句。', '再记一句。']) {
    await message.fill(answer)
    await send.click()
  }
  await message.fill('再问我一个问题')
  await send.click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('主动第 3 题')
  await message.fill('今天不想回答')
  await send.click()
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText('主动第 3 题')
  await page.getByText('邀请节奏与演示日期').click()
  await page.getByRole('button', { name: '推进到第 2 天' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('第 2 天 · 第 1 题')
  await expect(page.locator('.product-header-meta')).toContainText('每日两问')
})

test('an unrelated note does not rewrite the question already shown in the conversation', async ({ page }) => {
  await page.goto('/')
  const message = page.getByRole('textbox', { name: '发送消息' })
  const send = page.getByRole('button', { name: '发送', exact: true })
  await message.fill('随手记：下班时看到晚霞。')
  await send.click()
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('今天有什么想记下的？')
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText('你之前说“随手记：下班时看到晚霞。”')
  await message.fill('今天整理了书桌。')
  await send.click()
  await page.getByRole('button', { name: '画册' }).click()
  await expect(page.getByRole('region', { name: '已回答问题' })).toContainText('今天有什么想记下的？')
})

test('editing a cited record keeps its old wording out of a skipped-question bubble', async ({ page }) => {
  const old = '仅自己知道的旧词。'
  await page.goto('/')
  const message = page.getByRole('textbox', { name: '发送消息' })
  const send = page.getByRole('button', { name: '发送', exact: true })
  await message.fill(old)
  await send.click()
  await page.getByText('邀请节奏与演示日期').click()
  await page.getByRole('button', { name: '推进到第 2 天' }).click()
  await message.fill('跳过这一题')
  await send.click()
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText(old)
  await page.getByRole('button', { name: '画册' }).click()
  await page.getByRole('button', { name: '查看第 1 天' }).click()
  await page.getByRole('button', { name: '修改这条原话' }).click()
  await page.getByRole('textbox', { name: '修改原话' }).fill('现在保留的新词。')
  await page.getByRole('button', { name: '保存修改' }).click()
  await page.getByRole('navigation', { name: '产品导航' }).getByRole('button', { name: '对话' }).click()
  await expect(page.getByRole('region', { name: '对话记录' })).not.toContainText(old)
  await expect(page.getByRole('region', { name: '对话记录' })).toContainText('引用已修订')
})
