import '@testing-library/jest-dom/vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import App from '../../App'
import { DEMO_ROUNDS, PAST_RECORDS, REPLY_DELAY, REPLY_PART_DELAY, replyDuration, demoMarkdown, todayRecord } from './judgeScript'

beforeEach(() => { vi.useFakeTimers(); vi.spyOn(window, 'scrollTo').mockImplementation(() => {}); window.history.replaceState(null, '', '/?demo=judge') })
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers(); window.history.replaceState(null, '', '/') })

function sendRound() {
  const text = (screen.getByRole('textbox', { name: '预设消息' }) as HTMLTextAreaElement).value
  const round = DEMO_ROUNDS.find(round => round.user === text)!
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  act(() => vi.advanceTimersByTime(replyDuration(round)))
}

it('keeps a pending reply and the next message when moving through daily life and album, and resets daily choices', () => {
  const fetch = vi.spyOn(globalThis, 'fetch')
  const stored = vi.spyOn(Storage.prototype, 'getItem')
  render(<App />)
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  fireEvent.click(screen.getByRole('button', { name: '日常' }))
  expect(screen.getByRole('button', { name: '日常' })).toHaveAttribute('aria-current', 'page')
  const daily = screen.getByRole('region', { name: '日常生活记录' })
  expect(daily).toBeVisible()
  expect(screen.queryByRole('region', { name: '对话记录' })).not.toBeInTheDocument()
  fireEvent.click(within(daily).getByText('数据来源', { exact: true }))
  fireEvent.click(within(daily).getByLabelText('显示步数示例'))
  act(() => vi.advanceTimersByTime(replyDuration(DEMO_ROUNDS[0])))
  fireEvent.click(within(daily).getByRole('button', { name: '回到对话' }))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
  expect(screen.getByRole('region', { name: '对话记录' }).querySelectorAll('.product-bubble-row.user')).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', { name: '日常' }))
  expect(within(daily).getByLabelText('显示步数示例')).not.toBeChecked()
  fireEvent.click(within(daily).getByRole('button', { name: '翻开今天的画册' }))
  expect(screen.getByRole('region', { name: '每日画册' })).toHaveTextContent('好久没这么开心了')
  fireEvent.click(screen.getByRole('button', { name: '重新体验' }))
  fireEvent.click(screen.getByRole('button', { name: '日常' }))
  expect(screen.getByLabelText('显示步数示例')).toBeChecked()
  expect(fetch).not.toHaveBeenCalled()
  expect(stored).not.toHaveBeenCalled()
})

it('shows selected stickers only after their replies arrive and keeps partner changes and replay consistent', () => {
  render(<App />)
  const chat = screen.getByRole('region', { name: '对话记录' })
  expect(within(chat).queryByRole('img', { name: '知知开心地跳起来' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  act(() => vi.advanceTimersByTime(REPLY_DELAY - 1))
  expect(within(chat).queryByRole('img', { name: '知知开心地跳起来' })).not.toBeInTheDocument()
  act(() => vi.advanceTimersByTime(1))
  const happy = within(chat).getByRole('img', { name: '知知开心地跳起来' })
  expect(happy).toBeVisible()
  expect(within(chat).getByText(DEMO_ROUNDS[0].reply).compareDocumentPosition(happy) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  expect(within(chat).queryByRole('img', { name: '知知揉揉眼睛，准备休息' })).not.toBeInTheDocument()
  for (let index = 1; index < 5; index++) sendRound()
  expect(within(chat).getByRole('img', { name: '知知揉揉眼睛，准备休息' })).toBeVisible()
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(5)
  fireEvent.click(screen.getByLabelText('选择伙伴'))
  fireEvent.click(screen.getByRole('button', { name: '小笺，女性形象' }))
  expect(within(chat).queryByRole('img', { name: '知知开心地跳起来' })).not.toBeInTheDocument()
  expect(within(chat).queryByRole('img', { name: '知知揉揉眼睛，准备休息' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByLabelText('选择伙伴'))
  fireEvent.click(screen.getByRole('button', { name: '知知，默认形象' }))
  expect(within(chat).getByRole('img', { name: '知知开心地跳起来' })).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: '重新体验' }))
  expect(within(chat).queryByRole('img', { name: '知知开心地跳起来' })).not.toBeInTheDocument()
  expect(within(chat).queryByRole('img', { name: '知知揉揉眼睛，准备休息' })).not.toBeInTheDocument()
})

it('opens the exact historical source without advancing or losing the current conversation', () => {
  // JSDOM does not implement native dialog methods; real modal behavior is checked in the browser.
  Object.defineProperties(HTMLDialogElement.prototype, {
    showModal: { configurable: true, value: function (this: HTMLDialogElement) { this.open = true } },
    close: { configurable: true, value: function (this: HTMLDialogElement) { this.open = false; this.dispatchEvent(new Event('close')) } },
  })
  render(<App />)
  sendRound(); sendRound()
  fireEvent.click(screen.getByRole('button', { name: '查看 10月1日的原话' }))
  const source = screen.getByRole('dialog', { name: '这句话的来处' })
  expect(source).toHaveTextContent('昨天聚会很开心，返程过了零点。今天起床很累。')
  expect(source).not.toHaveTextContent('先把首页做好')
  fireEvent.click(within(source).getByRole('button', { name: '回到阅读' }))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[2].user)
  sendRound()
  const update = screen.getByRole('region', { name: '这次理解的变化' })
  expect(update).toHaveTextContent('已撤回')
  expect(update).toHaveTextContent('仍待确认')
  expect(within(update).queryByText('用户已确认')).not.toBeInTheDocument()
  sendRound()
  expect(update).toHaveTextContent('用户已确认')
})

it('puts the portrait before the collapsed transcript and keeps every original message accessible', () => {
  render(<App />)
  for (let index = 0; index < 5; index++) sendRound()
  fireEvent.click(screen.getByRole('button', { name: '查看画册' }))
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  const portrait = screen.getByRole('region', { name: '今日肖像' })
  const transcript = screen.getByText('完整对话 · 15 条').closest('details')!
  expect(transcript).not.toHaveAttribute('open')
  expect(portrait.compareDocumentPosition(transcript) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  fireEvent.click(screen.getByText('完整对话 · 15 条'))
  expect(transcript).toHaveAttribute('open')
  expect(transcript.querySelectorAll('.daily-message')).toHaveLength(15)
  expect(transcript).toHaveTextContent(DEMO_ROUNDS[2].user)
})

it('preserves both visits when returning and does not animate historical messages again', () => {
  render(<App />)
  for (let index = 0; index < 5; index++) sendRound()
  fireEvent.click(screen.getByRole('button', { name: '查看画册' }))
  fireEvent.click(screen.getByRole('button', { name: '体验下一次见面' }))
  const nextText = (screen.getByRole('textbox', { name: '预设消息' }) as HTMLTextAreaElement).value
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  act(() => vi.advanceTimersByTime(2000))
  expect(screen.queryByRole('textbox', { name: '预设消息' })).not.toBeInTheDocument()
  const chat = screen.getByRole('region', { name: '对话记录' })
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', { name: '← 回看昨天的对话' }))
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(5)
  expect(chat.querySelectorAll('.judge-message-enter')).toHaveLength(0)
  fireEvent.click(screen.getByRole('button', { name: '接着下一次见面 ↗' }))
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(1)
  expect(chat).toHaveTextContent(nextText)
  expect(chat.querySelectorAll('.judge-message-enter')).toHaveLength(0)
  fireEvent.click(screen.getByRole('button', { name: '查看画册' }))
  expect(screen.getByRole('region', { name: '每日画册' })).toHaveTextContent('先做一点，再慢慢改')
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  expect(screen.getByText('完整对话 · 4 条').closest('details')?.querySelectorAll('.daily-message')).toHaveLength(4)
})

it('uses corrected records in the next visit, archives only arrived replies and resets both visits safely', () => {
  const get = vi.spyOn(Storage.prototype, 'getItem')
  const fetch = vi.spyOn(globalThis, 'fetch')
  render(<App />)
  expect(screen.queryByRole('button', { name: '体验下一次见面' })).not.toBeInTheDocument()
  for (let index = 0; index < 5; index++) sendRound()
  fireEvent.click(screen.getByRole('button', { name: '查看画册' }))
  fireEvent.click(screen.getByRole('button', { name: '体验下一次见面' }))
  const chat = screen.getByRole('region', { name: '对话记录' })
  expect(chat).toHaveTextContent('昨天')
  expect(chat).toHaveTextContent('朋友认真听你讲项目')
  expect(chat).not.toHaveTextContent('聊天时一直提着劲')
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(0)
  const input = screen.getByRole('textbox', { name: '预设消息' })
  expect(input).toHaveAttribute('readonly')
  const nextText = (input as HTMLTextAreaElement).value
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  fireEvent.click(screen.getByRole('button', { name: '画册' }))
  fireEvent.click(screen.getByRole('button', { name: '阅读 2026年10月5日的记录' }))
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  expect(screen.getByRole('region', { name: '每日画册' })).toHaveTextContent(nextText)
  expect(screen.getByRole('region', { name: '每日画册' }).querySelectorAll('.daily-message')).toHaveLength(2)
  fireEvent.click(screen.getByRole('button', { name: '重新体验' }))
  act(() => vi.advanceTimersByTime(6000))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[0].user)
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(0)
  expect(get).not.toHaveBeenCalled()
  expect(fetch).not.toHaveBeenCalled()
})

it('advances preset turns, preserves the original correction and updates the album', () => {
  render(<App />)
  const input = screen.getByRole('textbox', { name: '预设消息' })
  expect(input).toHaveAttribute('readonly')
  const chat = screen.getByRole('region', { name: '对话记录' })
  expect(chat).not.toHaveTextContent(DEMO_ROUNDS[0].reply)
  sendRound()
  sendRound()
  fireEvent.click(screen.getByRole('button', { name: '画册' }))
  fireEvent.click(screen.getByRole('button', { name: '回到今天 ↗' }))
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  expect(screen.getByRole('region', { name: '今日肖像' })).toHaveTextContent('尚待用户确认')
  fireEvent.click(screen.getByRole('button', { name: '对话' }))
  for (let index = 2; index < DEMO_ROUNDS.length; index++) sendRound()
  expect(chat).toHaveTextContent(DEMO_ROUNDS[2].user)
  expect(screen.queryByRole('button', { name: '发送' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: '查看画册' }))
  expect(screen.getByRole('region', { name: '每日画册' })).toHaveTextContent('跟朋友待着其实很放松')
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  const portrait = screen.getByRole('region', { name: '今日肖像' })
  expect(portrait).toHaveTextContent('撤回“聊天时提着劲、聚会耗神”的猜测')
  expect(portrait).not.toHaveTextContent('暂定猜测：聊天时可能一直提着劲')
  expect(portrait).toHaveTextContent('用户已确认：这次开心与朋友认真倾听、关心未完成的项目有关')
  for (const reply of DEMO_ROUNDS[1].replies) expect(screen.getByRole('region', { name: '每日画册' })).toHaveTextContent(reply)
})

it('blocks repeated sends and cancels a delayed reply when replayed', () => {
  render(<App />)
  const send = screen.getByRole('button', { name: '发送' })
  fireEvent.click(send)
  fireEvent.click(send)
  expect(send).toBeDisabled()
  expect(screen.getByRole('region', { name: '对话记录' }).querySelectorAll('.product-bubble-row.user')).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', { name: '重新体验' }))
  act(() => vi.advanceTimersByTime(REPLY_DELAY * 2))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[0].user)
  expect(screen.getByRole('region', { name: '对话记录' })).not.toHaveTextContent(DEMO_ROUNDS[0].reply)
  sendRound()
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
})

it('delivers separate bubbles in order, locks the next turn and archives only the parts that have arrived', () => {
  render(<App />)
  sendRound()
  const send = screen.getByRole('button', { name: '发送' })
  const chat = screen.getByRole('region', { name: '对话记录' })
  fireEvent.click(send)
  act(() => vi.advanceTimersByTime(REPLY_DELAY))
  expect(within(chat).getByText(DEMO_ROUNDS[1].replies[0])).toBeVisible()
  expect(within(chat).queryByText(DEMO_ROUNDS[1].replies[1]!)).not.toBeInTheDocument()
  expect(send).toBeDisabled()
  fireEvent.click(send)
  expect(chat.querySelectorAll('.product-bubble-row.user')).toHaveLength(2)
  fireEvent.click(screen.getByRole('button', { name: '画册' }))
  fireEvent.click(screen.getByRole('button', { name: '回到今天 ↗' }))
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  const album = screen.getByRole('region', { name: '每日画册' })
  expect(album).toHaveTextContent(DEMO_ROUNDS[1].replies[0])
  expect(album).not.toHaveTextContent(DEMO_ROUNDS[1].replies[1]!)
  act(() => vi.advanceTimersByTime(REPLY_PART_DELAY))
  expect(album).toHaveTextContent(DEMO_ROUNDS[1].replies[1]!)
  fireEvent.click(screen.getByRole('button', { name: '对话' }))
  expect(send).toBeEnabled()
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[2].user)

  fireEvent.click(send)
  act(() => vi.advanceTimersByTime(REPLY_DELAY))
  expect(within(chat).getByText(DEMO_ROUNDS[2].replies[0])).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: '重新体验' }))
  act(() => vi.advanceTimersByTime(REPLY_PART_DELAY * 2))
  expect(chat).not.toHaveTextContent(DEMO_ROUNDS[2].replies[1]!)
  expect(chat.querySelectorAll('.product-bubble-row.agent')).toHaveLength(1)
})

it('does not access personal session storage or the model API, including replay and browsing', () => {
  const get = vi.spyOn(Storage.prototype, 'getItem')
  const set = vi.spyOn(Storage.prototype, 'setItem')
  const remove = vi.spyOn(Storage.prototype, 'removeItem')
  const fetch = vi.spyOn(globalThis, 'fetch')
  render(<App />)
  sendRound()
  fireEvent.click(screen.getByRole('button', { name: '画册' }))
  fireEvent.click(within(screen.getByLabelText('画册月份目录')).getByRole('button', { name: '2026年9月' }))
  fireEvent.click(screen.getByRole('button', { name: '阅读 2026年9月28日的记录' }))
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  fireEvent.click(screen.getByText('查看 Markdown 源文件'))
  fireEvent.click(screen.getByRole('button', { name: '重新体验' }))
  expect(get).not.toHaveBeenCalled()
  expect(set).not.toHaveBeenCalled()
  expect(remove).not.toHaveBeenCalled()
  expect(fetch).not.toHaveBeenCalled()
})

it('keeps pending turns when switching tabs and cleans up on unmount', () => {
  const view = render(<App />)
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  fireEvent.click(screen.getByRole('button', { name: '画册' }))
  fireEvent.click(screen.getByRole('button', { name: '回到今天 ↗' }))
  fireEvent.click(screen.getByRole('button', { name: '原话与理解' }))
  expect(screen.getByRole('region', { name: '每日画册' })).toHaveTextContent(DEMO_ROUNDS[0].user)
  expect(screen.getByRole('region', { name: '每日画册' })).not.toHaveTextContent(DEMO_ROUNDS[0].reply)
  act(() => vi.advanceTimersByTime(REPLY_DELAY))
  fireEvent.click(screen.getByRole('button', { name: '对话' }))
  expect(within(screen.getByRole('region', { name: '对话记录' })).getByText(DEMO_ROUNDS[0].reply)).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: '发送' }))
  view.unmount()
  act(() => vi.advanceTimersByTime(0))
  expect(vi.getTimerCount()).toBe(0)
})

it('archives only arrived messages with valid user evidence and explicitly synthetic Markdown', () => {
  const today = todayRecord(DEMO_ROUNDS.length)
  for (const record of [...PAST_RECORDS, todayRecord(2), today]) {
    for (const observation of record.portrait.observations) {
      expect(observation.evidenceIds.length).toBeGreaterThan(0)
      for (const id of observation.evidenceIds) expect(record.messages.find(message => message.id === id)?.role).toBe('user')
    }
    expect(record.model).toBeUndefined()
  }
  expect(todayRecord(0).diary).toBe('')
  expect(todayRecord(2).messages).toHaveLength(6)
  expect(todayRecord(2).messages.some(message => message.text === DEMO_ROUNDS[2].user)).toBe(false)
  const markdown = demoMarkdown(today)
  expect(markdown).toContain('不代表实时模型生成或真实用户数据')
  expect(markdown).toContain(DEMO_ROUNDS[2].user)
  for (const reply of DEMO_ROUNDS[1].replies) expect(markdown).toContain(reply)
  expect(markdown).toContain('暂不确认因果')
})

it('keeps deeper understanding provisional until the user confirms it and separates fatigue from the emotional experience', () => {
  const corrected = todayRecord(3)
  expect(corrected.portrait.observations[0].text).toContain('用户认为可能是返程折腾')
  expect(corrected.portrait.observations[1].text).toContain('尚待用户确认')
  expect(corrected.portrait.observations[1].evidenceIds).not.toContain('judge-user-4')
  expect(corrected.diary).not.toContain('那一刻，觉得自己没在一个人闷头折腾')
  expect(corrected.diary).not.toContain('今晚早点休息')

  const confirmed = todayRecord(4)
  const understanding = confirmed.portrait.observations[1]
  expect(understanding.text).toContain('用户已确认')
  expect(understanding.text).toContain('仅描述这次经历')
  expect(understanding.evidenceIds).toEqual(['judge-user-2', 'judge-user-4'])
  expect(confirmed.diary).toContain('身体累，心里倒是挺亮的')
  expect(confirmed.diary).not.toContain('今晚早点休息')
  expect(confirmed.portrait.uncertainties).toContain('疲惫的具体原因尚未确认，不能从晚归时间或两次聚会后的疲惫直接推断因果。')
  expect(todayRecord(DEMO_ROUNDS.length).diary).toContain('今晚早点休息')
})

it('switches companion images throughout the chat while preserving the scripted progress', () => {
  render(<App />)
  sendRound()
  fireEvent.click(screen.getByLabelText('选择伙伴'))
  fireEvent.click(screen.getByRole('button', { name: '小笺，女性形象' }))
  expect(screen.getByRole('heading', { name: '小笺' })).toBeVisible()
  expect(screen.getByLabelText('选择伙伴').closest('details')).not.toHaveAttribute('open')
  expect(screen.getByLabelText('选择伙伴')).toHaveFocus()
  const avatars = screen.getByRole('region', { name: '对话记录' }).querySelectorAll('.product-avatar-companion img')
  expect(avatars.length).toBeGreaterThan(1)
  for (const avatar of avatars) expect(avatar).toHaveAttribute('src', '/brand/characters/jianji-xiaojian-cutout.png')
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
  fireEvent.click(screen.getByLabelText('选择伙伴'))
  fireEvent.keyDown(screen.getByLabelText('选择伙伴'), { key: 'Escape' })
  expect(screen.getByLabelText('选择伙伴').closest('details')).not.toHaveAttribute('open')
})

it('previews voice input without recording or advancing a turn until send is clicked', () => {
  const getUserMedia = vi.fn()
  vi.stubGlobal('navigator', { mediaDevices: { getUserMedia } })
  const fetch = vi.spyOn(globalThis, 'fetch')
  render(<App />)
  fireEvent.click(screen.getByRole('button', { name: '开始语音输入' }))
  expect(screen.getByRole('region', { name: '对话记录' })).toHaveTextContent('无需录音')
  expect(screen.getByRole('button', { name: '发送' })).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: '停止聆听并放弃本次语音' }))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[0].user)
  fireEvent.click(screen.getByRole('button', { name: '开始语音输入' }))
  fireEvent.click(screen.getByRole('button', { name: '结束聆听并转成文字' }))
  expect(screen.getByRole('region', { name: '对话记录' }).querySelectorAll('.product-bubble-row.user')).toHaveLength(0)
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[0].user)
  sendRound()
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
  expect(getUserMedia).not.toHaveBeenCalled()
  expect(fetch).not.toHaveBeenCalled()
})

it('shares progress between call and chat, exits safely during a pending reply and clears the call timer', () => {
  const getUserMedia = vi.fn()
  vi.stubGlobal('navigator', { mediaDevices: { getUserMedia } })
  const get = vi.spyOn(Storage.prototype, 'getItem')
  const set = vi.spyOn(Storage.prototype, 'setItem')
  const fetch = vi.spyOn(globalThis, 'fetch')
  const view = render(<App />)
  fireEvent.click(screen.getByRole('button', { name: '语音对话' }))
  const call = screen.getByRole('region', { name: '渐知语音通话' })
  expect(call).toHaveTextContent('无需录音，不播放声音')
  expect(screen.queryByRole('region', { name: '对话记录' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: '开始语音对话聆听' }))
  const send = screen.getByRole('button', { name: '说完了，转写并发送' })
  fireEvent.click(send)
  fireEvent.click(send)
  act(() => vi.advanceTimersByTime(1000))
  expect(send).toBeDisabled()
  fireEvent.keyDown(screen.getByRole('button', { name: '退出语音通话' }), { key: 'Escape' })
  expect(screen.queryByRole('region', { name: '渐知语音通话' })).not.toBeInTheDocument()
  act(() => vi.advanceTimersByTime(REPLY_DELAY))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
  expect(screen.getByRole('region', { name: '对话记录' }).querySelectorAll('.product-bubble-row.user')).toHaveLength(1)
  fireEvent.click(screen.getByRole('button', { name: '语音对话' }))
  expect(screen.getByRole('region', { name: '渐知语音通话' })).toHaveTextContent(DEMO_ROUNDS[0].reply)
  expect(screen.getByRole('heading', { name: '准备听你说' })).toBeVisible()
  view.unmount()
  act(() => vi.advanceTimersByTime(0))
  expect(vi.getTimerCount()).toBe(0)
  expect(getUserMedia).not.toHaveBeenCalled()
  expect(get).not.toHaveBeenCalled()
  expect(set).not.toHaveBeenCalled()
  expect(fetch).not.toHaveBeenCalled()
})

it('discards a call transcript if exited before it has finished, keeping the next preset intact', () => {
  render(<App />)
  fireEvent.click(screen.getByRole('button', { name: '语音对话' }))
  fireEvent.click(screen.getByRole('button', { name: '开始语音对话聆听' }))
  fireEvent.click(screen.getByRole('button', { name: '说完了，转写并发送' }))
  fireEvent.click(screen.getByRole('button', { name: '退出语音通话' }))
  act(() => vi.advanceTimersByTime(REPLY_DELAY * 3))
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[0].user)
  expect(screen.getByRole('region', { name: '对话记录' }).querySelectorAll('.product-bubble-row.user')).toHaveLength(0)
  sendRound()
  expect(screen.getByRole('textbox', { name: '预设消息' })).toHaveValue(DEMO_ROUNDS[1].user)
})
